-- 코드를 입력하세요

# SELECT YEAR(B.SALES_DATE) YEAR,
# MONTH(B.SALES_DATE) MONTH,
# COUNT(DISTINCT B.USER_ID) PUCHASEDUSERS,
# ROUND(COUNT(DISTINCT B.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = '2021'),1) PUCHASEDRATIO
# FROM USER_INFO AS A LEFT JOIN ONLINE_SALE AS B ON A.USER_ID = B.USER_ID
# WHERE YEAR(A.JOINED) = '2021' AND B.SALES_DATE IS NOT NULL
# GROUP BY 1, 2
# ORDER BY 1, 2

SELECT 
YEAR(B.SALES_DATE) YEAR,
MONTH(B.SALES_DATE) MONTH,
COUNT(DISTINCT B.USER_ID) PUCHASEDUSERS,
ROUND(COUNT(DISTINCT B.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = '2021'),1) PUCHASEDRATIO
FROM USER_INFO AS A 
RIGHT JOIN ONLINE_SALE AS B  
ON A.USER_ID = B.USER_ID
WHERE A.JOINED LIKE '2021%'
GROUP BY 1, 2
ORDER BY YEAR, MONTH;