-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, (A.PRICE * SUM(AMOUNT)) AS TOTAL_SALES
FROM FOOD_PRODUCT AS A
LEFT JOIN FOOD_ORDER AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE B.PRODUCE_DATE LIKE '%2022-05%'
GROUP BY A.PRODUCT_ID
ORDER BY 3 DESC,1;